plugins {
    id "org.jetbrains.kotlin.jvm" version "2.3.20-Beta2"
    id "org.jetbrains.kotlin.kapt" version "2.3.20-Beta2"

    id "org.jlleitschuh.gradle.ktlint" version "14.0.1"
    id "io.gitlab.arturbosch.detekt" version "1.23.8"

    id "com.gradleup.shadow" version "9.3.1"
    id "application"

    // Check vor updates with `gradle-upgrade-interactive` (npm package)
    id "com.github.ben-manes.versions" version "0.53.0"
}

apply from: "$rootDir/gradle/plugins/klint.gradle"
apply from: "$rootDir/gradle/plugins/detekt.gradle"

group = "de.fnelles"
version = "1.0-SNAPSHOT"

application {
    mainClass = "core/BackendKt"
}

shadowJar {
    mergeServiceFiles()
}

repositories {
    mavenCentral()
    maven { url = "https://repo1.maven.org/maven2/" }
}

dependencies {
    implementation("io.github.cdimascio:dotenv-kotlin:6.5.1")

    implementation("io.javalin:javalin-bundle:6.7.0")
    implementation("io.javalin.community.openapi:javalin-openapi-plugin:7.0.0")
    kapt("io.javalin.community.openapi:openapi-annotation-processor:7.0.0")
    annotationProcessor("io.javalin.community.openapi:openapi-annotation-processor:7.0.0")

    def brotliVersion = "1.20.0"
    implementation("com.aayushatharva.brotli4j:brotli4j:$brotliVersion")
    implementation("com.aayushatharva.brotli4j:native-windows-x86_64:$brotliVersion")
    implementation("com.aayushatharva.brotli4j:native-windows-aarch64:$brotliVersion")
    implementation("com.aayushatharva.brotli4j:native-osx-aarch64:$brotliVersion")
    implementation("com.aayushatharva.brotli4j:native-linux-aarch64:$brotliVersion")
    implementation("com.aayushatharva.brotli4j:native-linux-x86_64:$brotliVersion")
    implementation("com.aayushatharva.brotli4j:native-linux-armv7:$brotliVersion")
    implementation("com.aayushatharva.brotli4j:native-linux-ppc64le:$brotliVersion")
    implementation("com.aayushatharva.brotli4j:native-linux-s390x:$brotliVersion")
    implementation("com.aayushatharva.brotli4j:native-linux-riscv64:$brotliVersion")
    implementation("io.swagger.core.v3:swagger-core:2.2.42")

    implementation("com.zaxxer:HikariCP:7.0.2")
    implementation("org.jdbi:jdbi3-core:3.51.0")
    implementation("org.jdbi:jdbi3-kotlin:3.51.0")
    implementation("org.jdbi:jdbi3-postgres:3.51.0")
    implementation("org.jdbi:jdbi3-kotlin-sqlobject:3.51.0")
    implementation("org.postgresql:postgresql:42.7.10")
    implementation("org.mariadb.jdbc:mariadb-java-client:3.5.7")
    implementation("org.flywaydb:flyway-core:12.0.1")
    implementation("org.flywaydb:flyway-mysql:12.0.1")

    def ktorVersion = "3.4.0"
    implementation("io.ktor:ktor-client-core:$ktorVersion")
    implementation("io.ktor:ktor-client-cio:$ktorVersion")
    implementation("io.ktor:ktor-client-content-negotiation:$ktorVersion")
    implementation("io.ktor:ktor-serialization-jackson:$ktorVersion")

    implementation("com.github.lookfirst:sardine:5.13")
    implementation("org.jsoup:jsoup:1.22.1")

    implementation("com.google.inject:guice:7.0.0")
    implementation("dev.misfitlabs.kotlinguice4:kotlin-guice:3.0.0")
    implementation("com.google.guava:guava:33.5.0-jre")

    implementation("org.slf4j:slf4j-simple:2.1.0-alpha1")

    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.21.0")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.21.0")
    implementation("de.undercouch:bson4jackson:2.18.0")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.3.20-Beta2")

    implementation("commons-codec:commons-codec:1.21.0")
    implementation("commons-io:commons-io:2.21.0")
    implementation("org.apache.commons:commons-compress:1.28.0")
    implementation("org.apache.commons:commons-lang3:3.20.0")

    implementation("net.lingala.zip4j:zip4j:2.11.6")

    implementation("at.favre.lib:bcrypt:0.10.2")

    implementation("io.github.furstenheim:copy_down:1.1")

    implementation("org.simplejavamail:simple-java-mail:8.12.6")
}

kotlin {
    jvmToolchain(17)
}
